### ISSUE TITLE
Hard coded hosts in `db_init.sh` should use env variables

### ISSUE THREAD

**Issue by Fmstrat** [porelli/firefox-sync#3]
Example: https://github.com/porelli/firefox-sync/blob/ac200e3c6be0da43bb4486787dca258e9c8e1ec0/syncstorage-rs/db_init.sh#L8

All hosts should use ENV variables for if users change their container names.

**Comment by porelli** [comment]
A different approach would be using the service name instead of the container name. This way, there is no need to maintain the name of the container both in the ENV variables and in the compose file. This is also what the documentation recommends but I missed to implement it the right way and I hardcoded `container_name`.

I will address it in the next commit.

**Comment by porelli** [comment]
Addressed in 84f06fc28248213c4c5a3850fe8124e144b60e16

Tested with 3 stacks in parallel, no conflicts.
